# Generated by Django 5.2.7 on 2025-10-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorpusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("clan", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transcriber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("translator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "orthography",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dialect", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_number", models.IntegerField()),
                ("sentence_tlingit", models.TextField()),
                ("sentence_english", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corpus_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="corpus.corpusentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("line_tlingit", models.TextField()),
                ("line_english", models.TextField()),
                ("page_tlingit", models.CharField(max_length=255)),
                ("page_english", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="corpus.sentence",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["sentence_tlingit"], name="corpus_sent_sentenc_16be75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["sentence_english"], name="corpus_sent_sentenc_2e19bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(
                fields=["line_tlingit"], name="corpus_line_line_tl_fff449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(
                fields=["line_english"], name="corpus_line_line_en_cca67f_idx"
            ),
        ),
    ]
